// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBREQe57d4eWf08LbIbLSYgZUBqgHNqPd4',
    appId: '1:843188534755:web:83a700f48063b6521234d6',
    messagingSenderId: '843188534755',
    projectId: 'block-e856b',
    authDomain: 'block-e856b.firebaseapp.com',
    storageBucket: 'block-e856b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-MbqJCivBQFdSeS9HiAUevL9RXn9aXno',
    appId: '1:843188534755:android:f08b621c82dd9f681234d6',
    messagingSenderId: '843188534755',
    projectId: 'block-e856b',
    storageBucket: 'block-e856b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7nmzfeIi1DMG8GnzIhU9Um2_9gxpMRQg',
    appId: '1:843188534755:ios:08296c20f7e26a411234d6',
    messagingSenderId: '843188534755',
    projectId: 'block-e856b',
    storageBucket: 'block-e856b.appspot.com',
    iosBundleId: 'com.example.sign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7nmzfeIi1DMG8GnzIhU9Um2_9gxpMRQg',
    appId: '1:843188534755:ios:08296c20f7e26a411234d6',
    messagingSenderId: '843188534755',
    projectId: 'block-e856b',
    storageBucket: 'block-e856b.appspot.com',
    iosBundleId: 'com.example.sign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBREQe57d4eWf08LbIbLSYgZUBqgHNqPd4',
    appId: '1:843188534755:web:8ba73acb8d577f931234d6',
    messagingSenderId: '843188534755',
    projectId: 'block-e856b',
    authDomain: 'block-e856b.firebaseapp.com',
    storageBucket: 'block-e856b.appspot.com',
  );
}
